services:
  - type: web_service
    name: rct-backend
    env: docker
    repo: rct-backend
    branch: release/v1.0.0
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8000"
    plan: starter
    region: iad
    envVars: